package ac.uk.jov2.dogsRus;

/**
 * 
 * @author Lynda Thomas and Chris Loftus
 * @version 1.0 (March 19th 2015)
 *
 */
public class Owner{

	private static int id;
	private int idAnimal;
	private String name;
	private String phone;
	
	public Owner(String n, String p) {
		this(-1, -1, n, p);
	}
	
	public Owner(int i, int idAnim, String n, String p) {
		id = i;
		phone = p;
		name= n;
		idAnimal = idAnim;
	}
	
	@Override
	public boolean equals(Object obj) { // Robust version generated by Eclipse (source menu)
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Owner other = (Owner) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (phone == null) {
			if (other.phone != null)
				return false;
		} else if (!phone.equals(other.phone))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return name + " " + phone;
	}

	public static int getId() {
		return id;
	}

	public static void setId(int i) {
		id = i;
	}

	public int getIdAnimal() {
		return idAnimal;
	}

	public void setIdAnimal(int idA) {
		idAnimal = idA;
	}

	public String getName() {
		return name;
	}

	public void setName(String n) {
		name = n;
	}
	
	public String getPhone() {
		return phone;
	}

	public void setPhone(String p) {
		phone = p;
	}

}
